#Arquivo de configurações
server:
  port: 8081

project:
  name: 'projeto_maven' #@valor@ está importando do .xml
  version: '1.0-SNAPSHOT'
  description: 'Exemplo de projeto Maven'
info:
  build:
    artifact: "projeto_maven"
    name: "projeto_maven"
    description: 'Exemplo de projeto Maven'
    version: '1.0-SNAPSHOT'

application:
  title: ${project.name}
  #${valor} é a forma Java de acessar o conteúdo de outro local, seja em memória ou de outro arquivo
  version: ${project.version}

  spring:
    output:
      ansi:
        enabled: ${SPRING_OUTPUT_ANSI_ENABLE} #always
    banner:
      charset: ${SPRING_BANNER_CHARSET} #UTF-8
      location: ${SPRING_BANNER_LOCATION} #classpath:/banner.txt

      #Logging
      logging:
        level:
          org.example.resource: debug
          br.senac.go: debug
          org.springframework.web: info